language: java
jdk:
- oraclejdk8
deploy:
  api_key:
    secure: kLqw96rXulO+d5vNcYMd72VIJBRTbIcUVGleuy0H+KPJQ+eZXBWvAHcZsPOb0r/f3h3GJZqV4DzCyPiP7SfGU8GnrdEtGbRo+1LN4i/vPnmcJFtccnPc64bskh1jA4b/8X+bNdArtWPKBV+94S2gJXhnyr4t6zFpSU0MkbLpF5qzInEw+keYl37F7oPlww0zPjOpv7yGw8VBIAttkawn226bsk8Ro+4Ps5+irxt6mPSE47ksOlt9OpI0CnD6KsQQLQkz2U1Dn6Jf2xJPiHHgEgSRJRRqJcNFh/VO6v3yZnpQzAM1A3uU51r/Dj/yaXl9KAZ8aY1oygkabhOrSfX2RYJywIvMWJF4SjnCiIqkP0nf9lLHhOY8ENXXoTRjTqwt5uYPsAtmrC0w4xkSpigOSrNe42KwthhK3jQPJFhdpmASKTVK7d42aPsKtadisfLM7V6f7BAABcoma9wY4X8fdJP5OsSozZgmjsCLOai3aUKRPB64CRZeMJu5J7BGQGzg26U6C6LeMjrJDsV6ua6sA3Px7GL3M8MFlWJSNLXzC54k72YEFaSyBxpS9H8baqYnkKbE+9v87wMBo+PUb1NjCa76hPf0shyDrOsIo7B9zu8HX9qolYxx1imGZLeJo3lNhyMsQnWOz+J4Lo/RJVMqA6wTyrghq+YCipSqKUI+iRk=
