language: java
jdk:
- oraclejdk8
deploy:
  provider: heroku
  app: gnnf-tictactoe
  api_key:
    secure: ZFuGdG2K4narBLlJZTdoek1A2Us4YKtdoMApCmQfPF28cVqkEiALmsHxf9DEMO4Y66mhJqSLTWMmGGDWCtmq7hBzjTFpz5Zrd/cSW3hmmx1bEp3rkwOkbF9k31r+9oQlK7FhzeVHLVrMnjbDQ1T11vNqc86D4W6feyuqoRuATFBFZDnhNZ8TSxy7Ljq5fZlZHW7qnyQJl+pM2TWGOdPFS8rKhKmFNNRwB1AWCHN9NnrzXuhYf1JvF5mkZ7KtMooYrX35fP9L4Fgt6dsnbm6kjdHTdBe2m3CmP+a5hYTgW80Et9zuJlp5KW3UDUtzb9/e1UF6ZH5qdVIa4lrEDdScRd+kkx/DErVyOZsM/tcDYq51BRVCF8bIubGKYCIXBeEaaeWX669tj6QC1YS7MpOSwg4+goU5Ab+arJ/XzcIJVM5394PMmASG3/HD+xrjG3rDzT1/xhqBlOCmpnCP71uJ8nhaK11Li0f/9A2DikZz79gDVKgKtYL9haNjsjHrbCDH6UC63uTwBJyOlTNm8eoIOd3Ceiw7SoFw+/8LbE+r6hjGr2wIhXT1RASOJ54nsXlnk5Kv0YkJ7oknSQ3iZc7/4cn/+RezOUwVs+DF5rDjvXqxSR0OBdtUlbPkyn+dxAYge9QWdgwLpiGZ1Jw/rnO032eBkI6CJvDNOyF2zooGh2I=
