/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'eyrunmagnusdottir' at '10/26/16 4:07 PM' with Gradle 3.1
 *
 * @author eyrunmagnusdottir, @date 10/26/16 4:07 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
